import jsPDF from "jspdf";
import type { Child, Profile, ReferralRecord, ScanRecord } from "@/shared/lib/types";
import {
  createConfidenceChartDataUrl,
  createHorizontalBarChartDataUrl,
  createRiskProfileChartDataUrl,
  createTextSummaryCardDataUrl,
  createTimelineChartDataUrl,
  loadImageDataUrl,
} from "@/shared/lib/reportGraphics";

const pageMargin = 14;
const colors = {
  primary: "#0F6E56",
  secondary: "#1D9E75",
  warning: "#854F0B",
  danger: "#A32D2D",
  white: "#FFFFFF",
  text: "#153229",
  muted: "#5D7069",
  border: "#D7E4DF",
  panel: "#F6FAF8",
};

const detectImageFormat = (dataUrl: string) => {
  if (dataUrl.startsWith("data:image/png")) return "PNG";
  if (dataUrl.startsWith("data:image/webp")) return "WEBP";
  return "JPEG";
};

const line = (doc: jsPDF, x1: number, y1: number, x2: number, y2: number) => {
  doc.setDrawColor(colors.border);
  doc.line(x1, y1, x2, y2);
};

const addContainedImage = (
  doc: jsPDF,
  imageData: string,
  x: number,
  y: number,
  width: number,
  height: number,
) => {
  const props = doc.getImageProperties(imageData);
  const imageRatio = props.width / props.height;
  const boxRatio = width / height;

  let renderWidth = width;
  let renderHeight = height;

  if (imageRatio > boxRatio) {
    renderHeight = width / imageRatio;
  } else {
    renderWidth = height * imageRatio;
  }

  const offsetX = x + (width - renderWidth) / 2;
  const offsetY = y + (height - renderHeight) / 2;

  doc.setFillColor(colors.white);
  doc.roundedRect(x, y, width, height, 3, 3, "F");
  doc.addImage(
    imageData,
    detectImageFormat(imageData),
    offsetX,
    offsetY,
    renderWidth,
    renderHeight,
    undefined,
    "FAST",
  );
};

const ensureSpace = (doc: jsPDF, y: number, required: number) => {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + required > pageHeight - pageMargin) {
    doc.addPage();
    return 18;
  }
  return y;
};

const writeWrapped = (doc: jsPDF, text: string, x: number, y: number, width: number, fontSize = 10, color = colors.text) => {
  doc.setFontSize(fontSize);
  doc.setTextColor(color);
  const wrapped = doc.splitTextToSize(text, width);
  doc.text(wrapped, x, y);
  return y + wrapped.length * (fontSize * 0.42 + 1.4);
};

const sectionTitle = (doc: jsPDF, title: string, y: number) => {
  doc.setFontSize(15);
  doc.setTextColor(colors.primary);
  doc.text(title, pageMargin, y);
  line(doc, pageMargin, y + 2, 196, y + 2);
  return y + 8;
};

const addImageBlock = (
  doc: jsPDF,
  title: string,
  imageData: string | null,
  y: number,
  height = 58,
) => {
  y = ensureSpace(doc, y, height + 18);
  y = sectionTitle(doc, title, y);
  if (imageData) {
    addContainedImage(doc, imageData, pageMargin, y, 182, height);
  } else {
    doc.setFillColor(colors.panel);
    doc.roundedRect(pageMargin, y, 182, height, 4, 4, "F");
    doc.setTextColor(colors.muted);
    doc.setFontSize(11);
    doc.text("Diagram unavailable for this export.", pageMargin + 8, y + 24);
  }
  return y + height + 8;
};

const addSummaryChips = (doc: jsPDF, entries: Array<[string, string]>, startY: number) => {
  let x = pageMargin;
  const y = startY;

  entries.forEach(([label, value]) => {
    const width = Math.max(44, Math.min(58, value.length * 3.2 + 22));
    doc.setFillColor(colors.panel);
    doc.roundedRect(x, y, width, 18, 4, 4, "F");
    doc.setTextColor(colors.muted);
    doc.setFontSize(8);
    doc.text(label, x + 4, y + 6.5);
    doc.setTextColor(colors.text);
    doc.setFontSize(10);
    doc.text(value, x + 4, y + 13);
    x += width + 4;
  });

  return y + 24;
};

const addHeader = (doc: jsPDF, title: string, subtitle: string) => {
  doc.setFillColor(colors.primary);
  doc.rect(0, 0, 210, 28, "F");
  doc.setTextColor("#FFFFFF");
  doc.setFontSize(22);
  doc.text(title, pageMargin, 14);
  doc.setFontSize(10);
  doc.text(subtitle, pageMargin, 21);
  return 38;
};

const addPatientDetails = (
  doc: jsPDF,
  scan: ScanRecord,
  child: Child,
  leftY: number,
  rightImage: string | null,
  author?: Profile,
) => {
  let y = leftY;
  doc.setFillColor(colors.panel);
  doc.roundedRect(pageMargin, y, rightImage ? 110 : 182, 50, 4, 4, "F");
  doc.setTextColor(colors.text);
  doc.setFontSize(14);
  doc.text("Patient summary", pageMargin + 6, y + 9);
  y = writeWrapped(doc, `Child: ${child.name}`, pageMargin + 6, y + 18, 98, 10);
  y = writeWrapped(doc, `DOB: ${child.dob}`, pageMargin + 6, y, 98, 10);
  y = writeWrapped(doc, `Scan date: ${new Date(scan.created_at).toLocaleString()}`, pageMargin + 6, y, 98, 10);
  y = writeWrapped(doc, `Variant: ${scan.variant.replaceAll("_", " ")}`, pageMargin + 6, y, 98, 10);
  if (author) {
    writeWrapped(doc, `Generated by: ${author.full_name}`, pageMargin + 6, y, 98, 10);
  }

  if (rightImage) {
    addContainedImage(doc, rightImage, 130, leftY, 66, 50);
  } else {
    doc.setFillColor(colors.panel);
    doc.roundedRect(130, leftY, 66, 50, 4, 4, "F");
    doc.setTextColor(colors.muted);
    doc.setFontSize(10);
    doc.text("Input image not available", 137, leftY + 26);
  }

  return leftY + 58;
};

export const downloadPatientReport = async (scan: ScanRecord, child: Child, language: "en" | "bn") => {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const inputImage = await loadImageDataUrl(scan.image_url);
  const confidenceChart = createConfidenceChartDataUrl(scan);
  const xaiChart = createHorizontalBarChartDataUrl(
    "Explainability attention",
    "Attention score by region",
    scan.xai_data.map((region) => ({
      label: region.region.replaceAll("_", " "),
      value: Math.round(region.attention * 100),
      color: colors.secondary,
    })),
  );
  const riskChart = createRiskProfileChartDataUrl(scan.comorbidity_flags);
  const timelineChart = createTimelineChartDataUrl(scan.surgical_windows, child);
  const summaryCard = createTextSummaryCardDataUrl("Care pathway summary", scan.care_pathway.map((item, index) => `${index + 1}. ${item.action} (${item.priority})`));

  let y = addHeader(
    doc,
    "GoldenScope AI Patient Report",
    language === "bn" ? "Patient-facing structured report with diagrams and explainability" : "Patient-facing structured report with diagrams and explainability",
  );

  y = addPatientDetails(doc, scan, child, y, inputImage);
  y = addSummaryChips(doc, [
    ["Classification", scan.classification],
    ["Confidence", `${Math.round(scan.confidence * 100)}%`],
    ["Severity", scan.severity],
    ["Variant", scan.variant.replaceAll("_", " ")],
  ], y);

  y = addImageBlock(doc, "Confidence and classification", confidenceChart, y, 64);
  y = addImageBlock(doc, "Explainability chart", xaiChart, y, 70);
  y = addImageBlock(doc, "Comorbidity risk chart", riskChart, y, 66);
  y = addImageBlock(doc, "Surgical timing diagram", timelineChart, y, 74);
  y = addImageBlock(doc, "Recommended care pathway", summaryCard, y, 58);

  y = ensureSpace(doc, y, 24);
  y = sectionTitle(doc, "Reminder", y);
  y = writeWrapped(doc, "Bring this report to your specialist appointment and discuss the highlighted attention regions, risk flags, and timing windows with your clinician.", pageMargin, y, 182, 11);
  writeWrapped(doc, `Generated by GoldenScope AI on ${new Date().toLocaleString()}.`, pageMargin, y + 2, 182, 10, colors.muted);

  doc.save(`goldenscope-patient-report-${child.name.toLowerCase().replace(/\s+/g, "-")}.pdf`);
};

export const downloadClinicalReport = async (
  scan: ScanRecord,
  child: Child,
  author: Profile,
  referral?: ReferralRecord,
) => {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const inputImage = await loadImageDataUrl(scan.image_url);
  const confidenceChart = createConfidenceChartDataUrl(scan);
  const segmentationChart = createHorizontalBarChartDataUrl(
    "Segmentation findings",
    "Detected structures and confidence levels",
    scan.segmentation_data.map((item) => ({
      label: `${item.label.replaceAll("_", " ")} (${item.side})`,
      value: Math.round(item.confidence * 100),
      color: colors.primary,
    })),
  );
  const riskChart = createRiskProfileChartDataUrl(scan.comorbidity_flags);
  const timelineChart = createTimelineChartDataUrl(scan.surgical_windows, child);
  const referralCard = referral
    ? createTextSummaryCardDataUrl("Referral summary", [
        `Specialty: ${referral.specialty}`,
        `Urgency: ${referral.urgency}`,
        `Status: ${referral.status}`,
        `Notes: ${referral.notes}`,
      ])
    : null;
  const icdCard = createTextSummaryCardDataUrl(
    "Clinical coding and notes",
    [
      `ICD-10 suggestions: ${(scan.icd10_codes || ["Q87.0", "H90.2"]).join(", ")}`,
      `Doctor notes: ${scan.doctor_notes || "No additional doctor notes recorded."}`,
      `Care pathway notes: ${scan.care_pathway_notes || "No additional pathway notes recorded."}`,
    ],
  );

  let y = addHeader(
    doc,
    "GoldenScope AI Clinical Report",
    "Structured clinical export with input image, explainability diagrams, and referral context",
  );

  y = addPatientDetails(doc, scan, child, y, inputImage, author);
  y = addSummaryChips(doc, [
    ["Classification", scan.classification],
    ["Confidence", `${Math.round(scan.confidence * 100)}%`],
    ["Severity", scan.severity],
    ["Variant", scan.variant.replaceAll("_", " ")],
  ], y);

  y = addImageBlock(doc, "Confidence and diagnostic overview", confidenceChart, y, 64);
  y = addImageBlock(doc, "Segmentation diagram", segmentationChart, y, 74);
  y = addImageBlock(doc, "Comorbidity risk diagram", riskChart, y, 66);
  y = addImageBlock(doc, "Surgical planning timeline", timelineChart, y, 74);
  y = addImageBlock(doc, "Coding and clinical notes", icdCard, y, 62);
  if (referralCard) {
    y = addImageBlock(doc, "Referral and follow-up", referralCard, y, 64);
  }

  y = ensureSpace(doc, y, 22);
  y = sectionTitle(doc, "Signature", y);
  y = writeWrapped(doc, `Clinician: ${author.full_name}`, pageMargin, y, 182, 11);
  y = writeWrapped(doc, "Signature: ____________________", pageMargin, y + 2, 182, 11);
  writeWrapped(doc, `Export generated ${new Date().toLocaleString()}`, pageMargin, y + 4, 182, 10, colors.muted);

  doc.save(`goldenscope-clinical-report-${child.name.toLowerCase().replace(/\s+/g, "-")}.pdf`);
};
